version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: chachamp
      MONGO_INITDB_ROOT_PASSWORD: Zxcv123!

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chachamp
      ME_CONFIG_MONGODB_ADMINPASSWORD: Zxcv123!
